/*
 * 88향법(八十八向法) — 88개 길향 전체표.
 *
 * 출처: docs/88_hyang_88_gilhyang_research.xlsx (문헌·웹 교차검증본)
 * 구성: 11개 향법 유형 × 목·화·금·수 4국 × 쌍산 2향 = 88행.
 *
 * 검산: 각 행의 '파구 궁위'(묘/절/태)가 lib/samhap.ts의 12포태 계산과 88/88 일치함을 확인했다.
 *
 * ⚠ 학술적으로 길흉 결과가 실증 검증된 이론이 아니다(박정해, 「88향법의 역사적 전개와
 *   논리 구성의 한계」, 역사와 융합 8(4), 2024). 국가·학계가 공인한 단일 공식표도 없다.
 *   자료 간 이견은 CAUTIONS에 병기한다.
 */

export interface Hyang88 {
  no: number;
  type: string;      // 향법 유형 (정생향 등)
  hanja: string;
  guk: "목국" | "화국" | "금국" | "수국";
  gung: "묘" | "절" | "태";   // 파구 궁위
  pagu: string;      // 파구 (정미(丁未) 등)
  flow: string;      // 수세 (우수도좌 / 좌수도우)
  pairHyang: string; // 쌍산 향
  hyang: string;     // 개별 향
  jwa: string;       // 개별 좌
  label: string;     // 좌향 표기
  cond: string;      // 필수·전승 조건
}

export const HYANG88: Hyang88[] = [
  {
    no: 1,
    type: "정생향",
    hanja: "正生向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "건(乾)",
    jwa: "손(巽)",
    label: "손좌건향(巽坐乾向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 2,
    type: "정생향",
    hanja: "正生向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "해(亥)",
    jwa: "사(巳)",
    label: "사좌해향(巳坐亥向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 3,
    type: "정생향",
    hanja: "正生向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "간(艮)",
    jwa: "곤(坤)",
    label: "곤좌간향(坤坐艮向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 4,
    type: "정생향",
    hanja: "正生向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "인(寅)",
    jwa: "신(申)",
    label: "신좌인향(申坐寅向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 5,
    type: "정생향",
    hanja: "正生向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "손(巽)",
    jwa: "건(乾)",
    label: "건좌손향(乾坐巽向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 6,
    type: "정생향",
    hanja: "正生向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "사(巳)",
    jwa: "해(亥)",
    label: "해좌사향(亥坐巳向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 7,
    type: "정생향",
    hanja: "正生向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "곤(坤)",
    jwa: "간(艮)",
    label: "간좌곤향(艮坐坤向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 8,
    type: "정생향",
    hanja: "正生向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "신(申)",
    jwa: "인(寅)",
    label: "인좌신향(寅坐申向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 9,
    type: "자생향",
    hanja: "自生向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "곤(坤)",
    jwa: "간(艮)",
    label: "간좌곤향(艮坐坤向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 10,
    type: "자생향",
    hanja: "自生向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "신(申)",
    jwa: "인(寅)",
    label: "인좌신향(寅坐申向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 11,
    type: "자생향",
    hanja: "自生向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "건(乾)",
    jwa: "손(巽)",
    label: "손좌건향(巽坐乾向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 12,
    type: "자생향",
    hanja: "自生向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "해(亥)",
    jwa: "사(巳)",
    label: "사좌해향(巳坐亥向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 13,
    type: "자생향",
    hanja: "自生向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "간(艮)",
    jwa: "곤(坤)",
    label: "곤좌간향(坤坐艮向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 14,
    type: "자생향",
    hanja: "自生向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "인(寅)",
    jwa: "신(申)",
    label: "신좌인향(申坐寅向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 15,
    type: "자생향",
    hanja: "自生向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "손(巽)",
    jwa: "건(乾)",
    label: "건좌손향(乾坐巽向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 16,
    type: "자생향",
    hanja: "自生向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "사(巳)",
    jwa: "해(亥)",
    label: "해좌사향(亥坐巳向)",
    cond: "향상작국; 좌선룡이 원칙"
  },
  {
    no: 17,
    type: "정왕향",
    hanja: "正旺向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "좌수도우",
    pairHyang: "갑묘(甲卯)",
    hyang: "갑(甲)",
    jwa: "경(庚)",
    label: "경좌갑향(庚坐甲向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 18,
    type: "정왕향",
    hanja: "正旺向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "좌수도우",
    pairHyang: "갑묘(甲卯)",
    hyang: "묘(卯)",
    jwa: "유(酉)",
    label: "유좌묘향(酉坐卯向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 19,
    type: "정왕향",
    hanja: "正旺向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "좌수도우",
    pairHyang: "병오(丙午)",
    hyang: "병(丙)",
    jwa: "임(壬)",
    label: "임좌병향(壬坐丙向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 20,
    type: "정왕향",
    hanja: "正旺向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "좌수도우",
    pairHyang: "병오(丙午)",
    hyang: "오(午)",
    jwa: "자(子)",
    label: "자좌오향(子坐午向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 21,
    type: "정왕향",
    hanja: "正旺向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "좌수도우",
    pairHyang: "경유(庚酉)",
    hyang: "경(庚)",
    jwa: "갑(甲)",
    label: "갑좌경향(甲坐庚向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 22,
    type: "정왕향",
    hanja: "正旺向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "좌수도우",
    pairHyang: "경유(庚酉)",
    hyang: "유(酉)",
    jwa: "묘(卯)",
    label: "묘좌유향(卯坐酉向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 23,
    type: "정왕향",
    hanja: "正旺向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "좌수도우",
    pairHyang: "임자(壬子)",
    hyang: "임(壬)",
    jwa: "병(丙)",
    label: "병좌임향(丙坐壬向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 24,
    type: "정왕향",
    hanja: "正旺向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "좌수도우",
    pairHyang: "임자(壬子)",
    hyang: "자(子)",
    jwa: "오(午)",
    label: "오좌자향(午坐子向)",
    cond: "우선룡이 원칙"
  },
  {
    no: 25,
    type: "자왕향",
    hanja: "自旺向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "좌수도우",
    pairHyang: "병오(丙午)",
    hyang: "병(丙)",
    jwa: "임(壬)",
    label: "임좌병향(壬坐丙向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 26,
    type: "자왕향",
    hanja: "自旺向",
    guk: "목국",
    gung: "묘",
    pagu: "정미(丁未)",
    flow: "좌수도우",
    pairHyang: "병오(丙午)",
    hyang: "오(午)",
    jwa: "자(子)",
    label: "자좌오향(子坐午向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 27,
    type: "자왕향",
    hanja: "自旺向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "좌수도우",
    pairHyang: "경유(庚酉)",
    hyang: "경(庚)",
    jwa: "갑(甲)",
    label: "갑좌경향(甲坐庚向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 28,
    type: "자왕향",
    hanja: "自旺向",
    guk: "화국",
    gung: "묘",
    pagu: "신술(辛戌)",
    flow: "좌수도우",
    pairHyang: "경유(庚酉)",
    hyang: "유(酉)",
    jwa: "묘(卯)",
    label: "묘좌유향(卯坐酉向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 29,
    type: "자왕향",
    hanja: "自旺向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "좌수도우",
    pairHyang: "임자(壬子)",
    hyang: "임(壬)",
    jwa: "병(丙)",
    label: "병좌임향(丙坐壬向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 30,
    type: "자왕향",
    hanja: "自旺向",
    guk: "금국",
    gung: "묘",
    pagu: "계축(癸丑)",
    flow: "좌수도우",
    pairHyang: "임자(壬子)",
    hyang: "자(子)",
    jwa: "오(午)",
    label: "오좌자향(午坐子向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 31,
    type: "자왕향",
    hanja: "自旺向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "좌수도우",
    pairHyang: "갑묘(甲卯)",
    hyang: "갑(甲)",
    jwa: "경(庚)",
    label: "경좌갑향(庚坐甲向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 32,
    type: "자왕향",
    hanja: "自旺向",
    guk: "수국",
    gung: "묘",
    pagu: "을진(乙辰)",
    flow: "좌수도우",
    pairHyang: "갑묘(甲卯)",
    hyang: "묘(卯)",
    jwa: "유(酉)",
    label: "유좌묘향(酉坐卯向)",
    cond: "향상작국; 우선룡이 원칙"
  },
  {
    no: 33,
    type: "정양향",
    hanja: "正養向",
    guk: "목국",
    gung: "절",
    pagu: "곤신(坤申)",
    flow: "우수도좌",
    pairHyang: "신술(辛戌)",
    hyang: "신(辛)",
    jwa: "을(乙)",
    label: "을좌신향(乙坐辛向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 34,
    type: "정양향",
    hanja: "正養向",
    guk: "목국",
    gung: "절",
    pagu: "곤신(坤申)",
    flow: "우수도좌",
    pairHyang: "신술(辛戌)",
    hyang: "술(戌)",
    jwa: "진(辰)",
    label: "진좌술향(辰坐戌向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 35,
    type: "정양향",
    hanja: "正養向",
    guk: "화국",
    gung: "절",
    pagu: "건해(乾亥)",
    flow: "우수도좌",
    pairHyang: "계축(癸丑)",
    hyang: "계(癸)",
    jwa: "정(丁)",
    label: "정좌계향(丁坐癸向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 36,
    type: "정양향",
    hanja: "正養向",
    guk: "화국",
    gung: "절",
    pagu: "건해(乾亥)",
    flow: "우수도좌",
    pairHyang: "계축(癸丑)",
    hyang: "축(丑)",
    jwa: "미(未)",
    label: "미좌축향(未坐丑向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 37,
    type: "정양향",
    hanja: "正養向",
    guk: "금국",
    gung: "절",
    pagu: "간인(艮寅)",
    flow: "우수도좌",
    pairHyang: "을진(乙辰)",
    hyang: "을(乙)",
    jwa: "신(辛)",
    label: "신좌을향(辛坐乙向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 38,
    type: "정양향",
    hanja: "正養向",
    guk: "금국",
    gung: "절",
    pagu: "간인(艮寅)",
    flow: "우수도좌",
    pairHyang: "을진(乙辰)",
    hyang: "진(辰)",
    jwa: "술(戌)",
    label: "술좌진향(戌坐辰向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 39,
    type: "정양향",
    hanja: "正養向",
    guk: "수국",
    gung: "절",
    pagu: "손사(巽巳)",
    flow: "우수도좌",
    pairHyang: "정미(丁未)",
    hyang: "정(丁)",
    jwa: "계(癸)",
    label: "계좌정향(癸坐丁向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 40,
    type: "정양향",
    hanja: "正養向",
    guk: "수국",
    gung: "절",
    pagu: "손사(巽巳)",
    flow: "우수도좌",
    pairHyang: "정미(丁未)",
    hyang: "미(未)",
    jwa: "축(丑)",
    label: "축좌미향(丑坐未向)",
    cond: "좌선룡이 원칙"
  },
  {
    no: 41,
    type: "정묘향",
    hanja: "正墓向",
    guk: "목국",
    gung: "절",
    pagu: "곤신(坤申)",
    flow: "좌수도우",
    pairHyang: "정미(丁未)",
    hyang: "정(丁)",
    jwa: "계(癸)",
    label: "계좌정향(癸坐丁向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 42,
    type: "정묘향",
    hanja: "正墓向",
    guk: "목국",
    gung: "절",
    pagu: "곤신(坤申)",
    flow: "좌수도우",
    pairHyang: "정미(丁未)",
    hyang: "미(未)",
    jwa: "축(丑)",
    label: "축좌미향(丑坐未向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 43,
    type: "정묘향",
    hanja: "正墓向",
    guk: "화국",
    gung: "절",
    pagu: "건해(乾亥)",
    flow: "좌수도우",
    pairHyang: "신술(辛戌)",
    hyang: "신(辛)",
    jwa: "을(乙)",
    label: "을좌신향(乙坐辛向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 44,
    type: "정묘향",
    hanja: "正墓向",
    guk: "화국",
    gung: "절",
    pagu: "건해(乾亥)",
    flow: "좌수도우",
    pairHyang: "신술(辛戌)",
    hyang: "술(戌)",
    jwa: "진(辰)",
    label: "진좌술향(辰坐戌向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 45,
    type: "정묘향",
    hanja: "正墓向",
    guk: "금국",
    gung: "절",
    pagu: "간인(艮寅)",
    flow: "좌수도우",
    pairHyang: "계축(癸丑)",
    hyang: "계(癸)",
    jwa: "정(丁)",
    label: "정좌계향(丁坐癸向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 46,
    type: "정묘향",
    hanja: "正墓向",
    guk: "금국",
    gung: "절",
    pagu: "간인(艮寅)",
    flow: "좌수도우",
    pairHyang: "계축(癸丑)",
    hyang: "축(丑)",
    jwa: "미(未)",
    label: "미좌축향(未坐丑向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 47,
    type: "정묘향",
    hanja: "正墓向",
    guk: "수국",
    gung: "절",
    pagu: "손사(巽巳)",
    flow: "좌수도우",
    pairHyang: "을진(乙辰)",
    hyang: "을(乙)",
    jwa: "신(辛)",
    label: "신좌을향(辛坐乙向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 48,
    type: "정묘향",
    hanja: "正墓向",
    guk: "수국",
    gung: "절",
    pagu: "손사(巽巳)",
    flow: "좌수도우",
    pairHyang: "을진(乙辰)",
    hyang: "진(辰)",
    jwa: "술(戌)",
    label: "술좌진향(戌坐辰向)",
    cond: "우선룡이 원칙; 우측 소수와 양수협출 조건"
  },
  {
    no: 49,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "목국",
    gung: "태",
    pagu: "경유(庚酉)",
    flow: "좌수도우",
    pairHyang: "곤신(坤申)",
    hyang: "곤(坤)",
    jwa: "간(艮)",
    label: "간좌곤향(艮坐坤向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 50,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "목국",
    gung: "태",
    pagu: "경유(庚酉)",
    flow: "좌수도우",
    pairHyang: "곤신(坤申)",
    hyang: "신(申)",
    jwa: "인(寅)",
    label: "인좌신향(寅坐申向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 51,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "화국",
    gung: "태",
    pagu: "임자(壬子)",
    flow: "좌수도우",
    pairHyang: "건해(乾亥)",
    hyang: "건(乾)",
    jwa: "손(巽)",
    label: "손좌건향(巽坐乾向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 52,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "화국",
    gung: "태",
    pagu: "임자(壬子)",
    flow: "좌수도우",
    pairHyang: "건해(乾亥)",
    hyang: "해(亥)",
    jwa: "사(巳)",
    label: "사좌해향(巳坐亥向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 53,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "금국",
    gung: "태",
    pagu: "갑묘(甲卯)",
    flow: "좌수도우",
    pairHyang: "간인(艮寅)",
    hyang: "간(艮)",
    jwa: "곤(坤)",
    label: "곤좌간향(坤坐艮向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 54,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "금국",
    gung: "태",
    pagu: "갑묘(甲卯)",
    flow: "좌수도우",
    pairHyang: "간인(艮寅)",
    hyang: "인(寅)",
    jwa: "신(申)",
    label: "신좌인향(申坐寅向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 55,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "수국",
    gung: "태",
    pagu: "병오(丙午)",
    flow: "좌수도우",
    pairHyang: "손사(巽巳)",
    hyang: "손(巽)",
    jwa: "건(乾)",
    label: "건좌손향(乾坐巽向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 56,
    type: "문고소수",
    hanja: "文庫消水",
    guk: "수국",
    gung: "태",
    pagu: "병오(丙午)",
    flow: "좌수도우",
    pairHyang: "손사(巽巳)",
    hyang: "사(巳)",
    jwa: "해(亥)",
    label: "해좌사향(亥坐巳向)",
    cond: "용혈 조건을 함께 확인"
  },
  {
    no: 57,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "우수도좌",
    pairHyang: "임자(壬子)",
    hyang: "임(壬)",
    jwa: "병(丙)",
    label: "병좌임향(丙坐壬向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 58,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "우수도좌",
    pairHyang: "임자(壬子)",
    hyang: "자(子)",
    jwa: "오(午)",
    label: "오좌자향(午坐子向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 59,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "우수도좌",
    pairHyang: "갑묘(甲卯)",
    hyang: "갑(甲)",
    jwa: "경(庚)",
    label: "경좌갑향(庚坐甲向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 60,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "우수도좌",
    pairHyang: "갑묘(甲卯)",
    hyang: "묘(卯)",
    jwa: "유(酉)",
    label: "유좌묘향(酉坐卯向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 61,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "우수도좌",
    pairHyang: "병오(丙午)",
    hyang: "병(丙)",
    jwa: "임(壬)",
    label: "임좌병향(壬坐丙向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 62,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "우수도좌",
    pairHyang: "병오(丙午)",
    hyang: "오(午)",
    jwa: "자(子)",
    label: "자좌오향(子坐午向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 63,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "우수도좌",
    pairHyang: "경유(庚酉)",
    hyang: "경(庚)",
    jwa: "갑(甲)",
    label: "갑좌경향(甲坐庚向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 64,
    type: "목욕소수",
    hanja: "沐浴消水",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "우수도좌",
    pairHyang: "경유(庚酉)",
    hyang: "유(酉)",
    jwa: "묘(卯)",
    label: "묘좌유향(卯坐酉向)",
    cond: "파구는 천간자; 지지자 침범 금기라는 전승 조건"
  },
  {
    no: 65,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "우수도좌",
    pairHyang: "경유(庚酉)",
    hyang: "경(庚)",
    jwa: "갑(甲)",
    label: "갑좌경향(甲坐庚向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 66,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "우수도좌",
    pairHyang: "경유(庚酉)",
    hyang: "유(酉)",
    jwa: "묘(卯)",
    label: "묘좌유향(卯坐酉向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 67,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "우수도좌",
    pairHyang: "임자(壬子)",
    hyang: "임(壬)",
    jwa: "병(丙)",
    label: "병좌임향(丙坐壬向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 68,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "우수도좌",
    pairHyang: "임자(壬子)",
    hyang: "자(子)",
    jwa: "오(午)",
    label: "오좌자향(午坐子向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 69,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "우수도좌",
    pairHyang: "갑묘(甲卯)",
    hyang: "갑(甲)",
    jwa: "경(庚)",
    label: "경좌갑향(庚坐甲向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 70,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "우수도좌",
    pairHyang: "갑묘(甲卯)",
    hyang: "묘(卯)",
    jwa: "유(酉)",
    label: "유좌묘향(酉坐卯向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 71,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "우수도좌",
    pairHyang: "병오(丙午)",
    hyang: "병(丙)",
    jwa: "임(壬)",
    label: "임좌병향(壬坐丙向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 72,
    type: "태향태류",
    hanja: "胎向胎流",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "우수도좌",
    pairHyang: "병오(丙午)",
    hyang: "오(午)",
    jwa: "자(子)",
    label: "자좌오향(子坐午向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 73,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "목국",
    gung: "절",
    pagu: "곤(坤)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "곤(坤)",
    jwa: "간(艮)",
    label: "간좌곤향(艮坐坤向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 74,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "목국",
    gung: "절",
    pagu: "곤(坤)",
    flow: "우수도좌",
    pairHyang: "곤신(坤申)",
    hyang: "신(申)",
    jwa: "인(寅)",
    label: "인좌신향(寅坐申向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 75,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "화국",
    gung: "절",
    pagu: "건(乾)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "건(乾)",
    jwa: "손(巽)",
    label: "손좌건향(巽坐乾向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 76,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "화국",
    gung: "절",
    pagu: "건(乾)",
    flow: "우수도좌",
    pairHyang: "건해(乾亥)",
    hyang: "해(亥)",
    jwa: "사(巳)",
    label: "사좌해향(巳坐亥向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 77,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "금국",
    gung: "절",
    pagu: "간(艮)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "간(艮)",
    jwa: "곤(坤)",
    label: "곤좌간향(坤坐艮向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 78,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "금국",
    gung: "절",
    pagu: "간(艮)",
    flow: "우수도좌",
    pairHyang: "간인(艮寅)",
    hyang: "인(寅)",
    jwa: "신(申)",
    label: "신좌인향(申坐寅向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 79,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "수국",
    gung: "절",
    pagu: "손(巽)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "손(巽)",
    jwa: "건(乾)",
    label: "건좌손향(乾坐巽向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 80,
    type: "절향절류",
    hanja: "絶向絶流",
    guk: "수국",
    gung: "절",
    pagu: "손(巽)",
    flow: "우수도좌",
    pairHyang: "손사(巽巳)",
    hyang: "사(巳)",
    jwa: "해(亥)",
    label: "해좌사향(亥坐巳向)",
    cond: "파구는 천간자; 백보전란·불견직거 조건"
  },
  {
    no: 81,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "좌수도우",
    pairHyang: "을진(乙辰)",
    hyang: "을(乙)",
    jwa: "신(辛)",
    label: "신좌을향(辛坐乙向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 82,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "목국",
    gung: "태",
    pagu: "경(庚)",
    flow: "좌수도우",
    pairHyang: "을진(乙辰)",
    hyang: "진(辰)",
    jwa: "술(戌)",
    label: "술좌진향(戌坐辰向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 83,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "좌수도우",
    pairHyang: "정미(丁未)",
    hyang: "정(丁)",
    jwa: "계(癸)",
    label: "계좌정향(癸坐丁向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 84,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "화국",
    gung: "태",
    pagu: "임(壬)",
    flow: "좌수도우",
    pairHyang: "정미(丁未)",
    hyang: "미(未)",
    jwa: "축(丑)",
    label: "축좌미향(丑坐未向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 85,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "좌수도우",
    pairHyang: "신술(辛戌)",
    hyang: "신(辛)",
    jwa: "을(乙)",
    label: "을좌신향(乙坐辛向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 86,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "금국",
    gung: "태",
    pagu: "갑(甲)",
    flow: "좌수도우",
    pairHyang: "신술(辛戌)",
    hyang: "술(戌)",
    jwa: "진(辰)",
    label: "진좌술향(辰坐戌向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 87,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "좌수도우",
    pairHyang: "계축(癸丑)",
    hyang: "계(癸)",
    jwa: "정(丁)",
    label: "정좌계향(丁坐癸向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  },
  {
    no: 88,
    type: "쇠향태류",
    hanja: "衰向胎流",
    guk: "수국",
    gung: "태",
    pagu: "병(丙)",
    flow: "좌수도우",
    pairHyang: "계축(癸丑)",
    hyang: "축(丑)",
    jwa: "미(未)",
    label: "미좌축향(未坐丑向)",
    cond: "혈 앞 유입→좌회전→혈 뒤 파구; 평지형 조건"
  }
];

/** 자료 간 이견 — 판정을 단정하지 않기 위해 함께 보여 준다 */
export const CAUTIONS: { topic: string; fact: string }[] = [
  { topic: "‘정본’의 의미", fact: "국가·학계가 공인한 단일 공식 88향 표는 확인되지 않음." },
  { topic: "정향/변향 분류", fact: "기모아 계열은 절향절류를 정국으로, 경북신문 칼럼은 변향으로 분류." },
  { topic: "88향과 96향", fact: "일부 학설은 묘향묘파 8향을 추가하여 96향으로 봄." },
  { topic: "파구 표기", fact: "일부 유형은 쌍산(2자), 일부는 천간자 단독으로 파구를 제한." },
  { topic: "88행 확장 방식", fact: "원자료는 44개의 쌍산 향으로 제시되는 경우가 많음." },
  { topic: "측정 층위", fact: "좌향과 물의 방위는 같은 나경 층을 쓰지 않는다고 설명하는 국내 자료가 있음." },
  { topic: "과학적 검증", fact: "2024년 KCI 논문은 길흉 결과가 실증적으로 검증되지 않았다고 지적." },
];

/** 근거 자료 */
export const SOURCES: { name: string; by: string; url: string; level: string }[] = [
  { name: "88향법의 역사적 전개와 논리 구성의 한계", by: "박정해, 역사와 융합 8(4), 2024", url: "https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART003110612", level: "높음(학술)" },
  { name: "88향법", by: "한국민족문화대백과사전", url: "https://encykorea.aks.ac.kr/Article/E0059757", level: "높음(기관 편찬)" },
  { name: "풍수 88향법의 환경분석적 연구방향의 모색", by: "ScienceON/KISTI", url: "https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=NPAP08118700", level: "높음(학술 DB)" },
  { name: "팔십팔향법 11종 전체 조합", by: "시골길 하얀초가집(전재 자료)", url: "https://sipjangsaeng.tistory.com/17163460", level: "중간(2차 자료)" },
  { name: "팔십팔향법의 종류 및 개별 유형", by: "기모아 패철 사용법", url: "https://m.gimoa.kr/article/%ED%8C%A8%EC%B2%A0-%EC%82%AC%EC%9A%A9%EB%B2%95/15/133/", level: "중간(2차 자료)" },
  { name: "팔십팔향법 운용 원칙", by: "경북신문 양삼열 칼럼 181", url: "https://www.kbsm.net/news/view.php?idx=476733", level: "중간(전문가 칼럼)" },
  { name: "정생향과 자생향", by: "경북신문 양삼열 칼럼 182", url: "https://www.kbsm.net/news/view.php?idx=478370", level: "중간(전문가 칼럼)" },
  { name: "정왕향과 자왕향", by: "경북신문 양삼열 칼럼 183", url: "https://www.kbsm.net/news/view.php?idx=479270", level: "중간(전문가 칼럼)" },
];
